# Generated by gallery/generate.py; do not edit.
function draconic_evolution_gallery:clear
fill 170 99 170 190 99 182 minecraft:stone
fill 187 96 175 189 99 177 minecraft:air
# basic-io: basic direct I/O crystal
setblock 172 100 172 draconicevolution:basic_io_crystal
# basic-relay: basic relay crystal
setblock 176 100 172 draconicevolution:basic_relay_crystal
# basic-wireless: basic wireless crystal
setblock 180 100 172 draconicevolution:basic_wireless_crystal
# wyvern-io: wyvern direct I/O crystal
setblock 184 100 172 draconicevolution:wyvern_io_crystal
# wyvern-relay: wyvern relay crystal
setblock 188 100 172 draconicevolution:wyvern_relay_crystal
# wyvern-wireless: wyvern wireless crystal
setblock 172 100 176 draconicevolution:wyvern_wireless_crystal
# draconic-io: draconic direct I/O crystal
setblock 176 100 176 draconicevolution:draconic_io_crystal
# draconic-relay: draconic relay crystal
setblock 180 100 176 draconicevolution:draconic_relay_crystal
# draconic-wireless: draconic wireless crystal
setblock 184 100 176 draconicevolution:draconic_wireless_crystal
# chaos-crystal: chaos crystal static outer shell
setblock 188 100 176 draconicevolution:chaos_crystal
# draconium-chest: closed Draconium chest
setblock 172 100 180 draconicevolution:draconium_chest
# reactor-core: neutral reactor core
setblock 176 100 180 draconicevolution:reactor_core
# reactor-injector: idle reactor injector
setblock 180 100 180 draconicevolution:reactor_injector
# reactor-stabilizer: idle reactor stabilizer
setblock 184 100 180 draconicevolution:reactor_stabilizer
# stock-control: stone stock rendering control
setblock 188 100 180 minecraft:stone
function draconic_evolution_gallery:verify
