# Generated by gallery/generate.py; do not edit.
function draconic_evolution_gallery:clear
# stock-control: stone stock rendering control
setblock 176 100 175 minecraft:stone
function draconic_evolution_gallery:verify
