# Generated by gallery/generate.py; do not edit.
execute unless block 172 100 172 draconicevolution:basic_io_crystal run tellraw @a {"text":"gallery mismatch: basic-io","color":"red"}
execute unless block 176 100 172 draconicevolution:basic_relay_crystal run tellraw @a {"text":"gallery mismatch: basic-relay","color":"red"}
execute unless block 180 100 172 draconicevolution:basic_wireless_crystal run tellraw @a {"text":"gallery mismatch: basic-wireless","color":"red"}
execute unless block 184 100 172 draconicevolution:wyvern_io_crystal run tellraw @a {"text":"gallery mismatch: wyvern-io","color":"red"}
execute unless block 188 100 172 draconicevolution:wyvern_relay_crystal run tellraw @a {"text":"gallery mismatch: wyvern-relay","color":"red"}
execute unless block 172 100 176 draconicevolution:wyvern_wireless_crystal run tellraw @a {"text":"gallery mismatch: wyvern-wireless","color":"red"}
execute unless block 176 100 176 draconicevolution:draconic_io_crystal run tellraw @a {"text":"gallery mismatch: draconic-io","color":"red"}
execute unless block 180 100 176 draconicevolution:draconic_relay_crystal run tellraw @a {"text":"gallery mismatch: draconic-relay","color":"red"}
execute unless block 184 100 176 draconicevolution:draconic_wireless_crystal run tellraw @a {"text":"gallery mismatch: draconic-wireless","color":"red"}
execute unless block 188 100 176 draconicevolution:chaos_crystal run tellraw @a {"text":"gallery mismatch: chaos-crystal","color":"red"}
execute unless block 172 100 180 draconicevolution:draconium_chest run tellraw @a {"text":"gallery mismatch: draconium-chest","color":"red"}
execute unless block 176 100 180 draconicevolution:reactor_core run tellraw @a {"text":"gallery mismatch: reactor-core","color":"red"}
execute unless block 180 100 180 draconicevolution:reactor_injector run tellraw @a {"text":"gallery mismatch: reactor-injector","color":"red"}
execute unless block 184 100 180 draconicevolution:reactor_stabilizer run tellraw @a {"text":"gallery mismatch: reactor-stabilizer","color":"red"}
execute unless block 188 100 180 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Draconic Evolution gallery checked","color":"green"}
